# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "ums_realtek"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/45f8c7ea-cc90-489d-80a9-9005ddff6b16";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D0B7-FE03";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/1E2E-3DE1";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  fileSystems."/mnt/ssd" = {
    device = "/dev/disk/by-partuuid/e778a075-0f2c-4681-ac2d-4278d2a89858";
    fsType = "ntfs";
    options = [ "rw" ];
  };

  fileSystems."/home/lotus/Documents" = {
    device = "/t/shared/Documents";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/home/lotus/Downloads" = {
    device = "/mnt/shared/Downloads";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/home/lotus/Videos" = {
    device = "/mnt/shared/Videos";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/home/lotus/Games" = {
    device = "/mnt/shared/Games";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/home/lotus/drives/secondary" = {
    device = "/mnt/shared/";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/home/lotus/drives/ssd" = {
    device = "/mnt/ssd";
    fsType = "none";
    options = [ "bind" ];
  };

  swapDevices = [ ];

  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
    priority = 5;
  };

  boot.kernel.sysctl."vm.swappiness" = 100;

  services.earlyoom.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true;
  hardware.graphics.enable32Bit = true;
  services.pipewire.alsa.support32Bit = true;
}
