-- ── Autostart ───────────────────────────────────────────────────────
hl.on("hyprland.start", function()
	hl.exec_cmd("hypridle")
	hl.exec_cmd("[silent] bash ~/hm/scripts/obs-start.sh")
	hl.exec_cmd("noctalia")
	hl.exec_cmd("[workspace 1 silent] " .. term)
	-- hl.exec_cmd("LIBVA_DRIVER_NAME=i915 discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy")
	hl.exec_cmd("[silent] vesktop")
	hl.exec_cmd(browser)
	hl.exec_cmd(files)
	hl.exec_cmd("[silent] spotify")
	hl.exec_cmd("[silent] steam")
	hl.exec_cmd("kdeconnectd")
	hl.exec_cmd("kdeconnect-indicator")
	hl.exec_cmd("[silent] pavucontrol")
	hl.exec_cmd("[silent] speedcrunch")
	hl.exec_cmd("[silent] ghostty --class=com.ghostty.notes -e nvim -O ~/vaults/notes.md ~/vaults/todo.md")
end)
